Disable `jackson` json/xml parsing of `application/json` & `application/xml` multipart content.
Datameer X is not using this code.

### Why
Spring web app initialization fails with incompatible `Jackson` jars on the classpath with
```
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/exc/InvalidDefinitionException
	at org.springframework.http.converter.support.AllEncompassingFormHttpMessageConverter.<init>(AllEncompassingFormHttpMessageConverter.java:94)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.<init>(RequestMappingHandlerAdapter.java:216)
```

There is no flag in `spring` to disable the code, hence disable it in custom jar.